services:
  spring:
    container_name: mogaktae-server
    image: ${DOCKER_HUB_USERNAME}/mogaktae-server:latest
    ports:
      - "8070:8080"
    depends_on:
      - redis
      - es
    environment:
      - TZ=Asia/Seoul
    networks:
      - es-bridge

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: mogaktae-elasticsearch
    environment:
      - node.name=mogaktae-node
      - cluster.name=mogaktae-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-bridge

  kibana:
    container_name: mogaktae-kibana
    image: docker.elastic.co/kibana/kibana:8.5.3
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - es-bridge

  redis:
    image: redis:latest
    container_name: mogaktae-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6380:6379
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge