services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=xunxxoie
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-bridge

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.3
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - es-bridge

  redis:
    image: redis:latest
    container_name: mogaktae-redis
    command: redis-server --requirepass sider-eatkagom
    environment:
      - REDIS_PASSWORD=sider-eatkagom
    ports:
      - 6379:6379
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge