spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: true
        use_sql_comments: true
    open-in-view: false

  data:
    elasticsearch:
      repositories:
        enabled: true

    redis:
      host: mogaktae-redis
      port: 6379
      password: ${REDIS_PASSWORD}

  sql:
    init:
      mode: always
      data-locations:
        - classpath:sql/USER.sql
        - classpath:sql/CHALLENGE.sql
        - classpath:sql/USER_CHALLENGE.sql
      continue-on-error: false
      encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GIT_CLIENT_ID}
            client-secret: ${GIT_CLIENT_SECRET}

    jwt:
      secret: ${JWT_SECRET}

logging:
  level:
    root: INFO

sentry:
  dsn: "${SENTRY_DSN}"
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0

server:
  forward-headers-strategy: native